version: '2'

services:
  kotlin-spring-sample:
    build: .
    image: creditas/kotlin-spring-sample
    hostname: kotlin-spring-sample
    network_mode: host
    ports:
      - "80:8080"

networks:
  bankfacil:
    external: true
