version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - ./docker/postgres-multiple-databases.sh:/docker-entrypoint-initdb.d/postgres-multiple-databases.sh
    restart: always
    hostname: kotlin-spring-sample
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_MULTIPLE_DATABASES=kotlin_spring_sample,kotlin_spring_sample_test

  kotlin-spring-sample:
    build: .
    image: creditas/kotlin-spring-sample
    hostname: kotlin-spring-sample
    ports:
      - "80:8080"
    init: true
    depends_on:
      - db
    environment:
      - "DATABASE_URL=jdbc:postgresql://db:5432/kotlin_spring_sample?user=postgres"

networks:
  bankfacil:
    external: true
