version: '2'

services:
  kotlin-spring-sample:
    build: .
    image: creditas/kotlin-spring-sample
    hostname: kotlin-spring-sample
    networks:
      - bankfacil
    ports:
      - "80:9292"

networks:
  bankfacil:
    external: true
