context:
  initializer:
    classes: br.com.creditas.kotlinspringsample.configuration.WebConfiguration
logentries:
  token: ~
logging:
  level:
    org:
      zalando:
        logbook: TRACE
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} %highlight(%-5level) %magenta(%logger.%M) - %msg%n%rEx"
management:
  endpoints:
    web:
      base-path: ~
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/kotlin_spring_sample?user=postgres"
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
