logentries:
  token: ~
logging:
  level:
    org:
      zalando:
        logbook: TRACE
logbook:
  exclude:
    - /health
    - /favicon.ico
management:
  endpoints:
    web:
      base-path: ~
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/kotlin_spring_sample?user=postgres"
  flyway:
    enabled: false
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  data:
    mongodb:
      uri: ${MONGODB_DATABASE_URL}
