logging:
  level:
    org:
      zalando:
        logbook: TRACE
context:
  initializer:
    classes: br.com.creditas.kotlinspringsample.configuration.WebConfiguration
management:
  endpoints:
    web:
      base-path:
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/kotlin_spring_sample_test?user=postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
