logging:
  level:
    org:
      zalando:
        logbook: TRACE
context:
  initializer:
    classes: br.com.creditas.riskanalysis.web.configuration.WebConfiguration
management:
  endpoints:
    web:
      base-path:
spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true