version: 2.1

jobs:
  test:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/banquinho

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Run tests
          command: gradle test -i

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml"
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

  release:
    docker:
      - image: circleci/openjdk:11-jdk
        environment:
          EMAIL: dev@creditas.com.br
          GIT_AUTHOR_NAME: developer
          GIT_COMMITTER_NAME: developer

    working_directory: ~/banquinho

    steps:
      - checkout
      - run:
          name: Release
          command: gradle release -Prelease.useAutomaticVersion=true -x test

workflows:
  version: 2
  banquinho-deploy:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - master